security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_redirect_by_role
                username_parameter: 'email'    
                password_parameter: 'password'
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/enseignant, roles: ROLE_ENSEIGNANT }
        - { path: ^/etudiant, roles: ROLE_ETUDIANT }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ENSEIGNANT, ROLE_ETUDIANT]
        ROLE_ENSEIGNANT: [ROLE_USER]
        ROLE_ETUDIANT: [ROLE_USER]