framework:
    validation:
        email_validation_mode: html5
        not_compromised_password: true

        # Enables validator auto-mapping support.
        # This allows automatic validation based on Doctrine annotations.
        auto_mapping:
            App\Entity\: []
            
when@test:
    framework:
        validation:
            not_compromised_password: false
